### ISSUE TITLE
tengine支持

### ISSUE THREAD

**Issue by javafx2010** [didi/AoE#12]
我实测了一下，tengine性能比ncnn好不少，你们会不会考虑支持？😊
[OAID/Tengine](https://github.com/OAID/Tengine )

**Comment by Kuloud** [comment]
感谢推荐 ：）
Tengine 出自Open AI Lab，是arm平台的嵌入式终端推理计算框架，我们加到需求池里，增加支持。

**Comment by xuguozhi** [comment]
Tengine +1

**Comment by yangke1120** [comment]
已经添加tengine-runtime，使用tengine 1.12开源版本
