### ISSUE TITLE
Opencv Dnn 支持

### ISSUE THREAD

**Issue by 121786404** [didi/AoE#19]
在X86处理器上，OpenCV DNN 速度最快，希望能支持。

**Comment by Kuloud** [comment]
> 在X86处理器上，OpenCV DNN 速度最快，希望能支持。

您好，感谢您的建议。暂时没有适配 OpenCV 的计划
1 移动设备基本是arm架构
2 OpenCV DNN在终端侧的应用情况感觉非主流，常用的深度学习推理框架（TensorFlow/PyTorch/ NNN）适配和优化可能做的更好。
