### ISSUE TITLE
Resource Leak

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [didi/AoE#27]
Stream is opened

https://github.com/didi/AoE/blob/ae1cb2ff0249952f1086244060cf0b426b7661b0/linux/src/plugin/AOECrypto.c#L18

Opened file never closed

https://github.com/didi/AoE/blob/ae1cb2ff0249952f1086244060cf0b426b7661b0/linux/src/plugin/AOECrypto.c#L46

**Comment by Kuloud** [comment]
line 138 & 215 , too.
