### ISSUE TITLE
好久没看到更新了，这个是不是没人维护了？

### ISSUE THREAD

**Issue by ToBigboss** [didi/AoE#29]
**请描述你的问题（Is your feature request related to a problem? Please describe.）**

**请描述你的解决方案（Describe the solution you'd like）**

**其他信息（Additional context）**

**Comment by Kuloud** [comment]
> **请描述你的问题（Is your feature request related to a problem? Please describe.）**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **请描述你的解决方案（Describe the solution you'd like）**
> A clear and concise description of what you want to happen.
> 
> **其他信息（Additional context）**
> Add any other context or screenshots about the feature request here.

哈哈，不会，最近业务上比较忙，框架在内部有些迭代，没有整理出来。
框架会持续维护的哈，不要担心。

感谢关注和支持。

**Comment by xiaooquanwu** [comment]
好久没看到更新了，这个是不是没人维护了？
