### ISSUE TITLE
关于binder IPC性能数据的疑问

### ISSUE THREAD

**Issue by RickAi** [didi/AoE#9]
"这里，有两个因素造成了耗时损失，一是传输耗时，二是序列化/反序列化耗时。相比较使用Binder机制的传输耗时，序列化/反序列化占了整个通信耗时的90%。"

这里序列化耗时占用90%的数据是否严谨，可否给下数据来源、测试case

**Comment by zouyuefu** [comment]
这是一个好问题，我本来想写“序列化/反序列化占了整个通信耗时90%以上”，回头我修改一下。根据我们之前在小米8和小米5上面的测试数据来看，序列化/反序列化耗时实际占整个通信耗时分别是98.2%和97.1%。下面是我们之前基于人脸检测模型做的测试的数据。


机型 | 模型 | 统计次数 | 帧数据大小(byte) | Client帧数据处理A（ms） | Service帧数据处理P（ms） | 帧数据IO操作 O（ms） | 数据IPC传输I（ms） | 推理框架处理M（ms）
-- | -- | -- | -- | -- | -- | -- | -- | --
MI 8 | 人脸识别（input: float[1][96][91][1]output: float[1][30]ml: TensorFlow） | 6006 | 130066 | 131 | 130 | 55 | 1 | 75
HM 5 | 人脸识别（input: float[1][96][91][1]output: float[1][30]ml: TensorFlow） | 825 | 130066 | 195 | 193 | 68 | 2 | 125
